### ISSUE TITLE
Duplicate use

### ISSUE THREAD

**Issue by waghanza** [waghanza/book-manager#4]
Hi @paknahad,

With the latest stable of https://github.com/paknahad/jsonapi-bundle, **version** `1.2.2`, following command : 
~~~sh
php bin/console make:api Book
~~~

Generate a class with an error inside 

I have generate it here and I have a duplicate `use` here
https://github.com/waghanza/book-manager/blob/ce03342358b6411761ba712f3384edf28ac239b2/src/JsonApi/Hydrator/Book/AbstractBookHydrator.php#L12

Regards,

**Comment by paknahad** [comment]
Hi
Thanks
The issue fixed
